# Generated by Django 3.2.3 on 2021-05-31 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('like_app', '0002_auto_20210531_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='though',
            name='users_like',
            field=models.ManyToManyField(related_name='post_like', to='like_app.users'),
        ),
        migrations.AlterField(
            model_name='though',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='like_app.users'),
        ),
    ]
