# Generated by Django 2.2.4 on 2021-05-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
