# Generated by Django 2.2.4 on 2021-05-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20210525_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
