# Generated by Django 2.2.4 on 2021-06-03 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210602_1556'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserve',
        ),
    ]
