# Generated by Django 2.2.4 on 2021-06-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20210604_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='cate',
        ),
    ]
