# Generated by Django 2.2.4 on 2021-06-04 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_car_cate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
