# Generated by Django 2.2.4 on 2021-06-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20210604_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.CharField(max_length=255),
        ),
    ]
