# Generated by Django 2.2.4 on 2021-06-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20210604_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.TextField(default='company@company.com', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.TextField(default='company', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserve',
            name='pickup_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='return_time',
            field=models.DateField(),
        ),
    ]
