# Generated by Django 2.2.4 on 2021-06-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.BooleanField(),
        ),
    ]
